services:
  cache:
    container_name: ddev-${DDEV_SITENAME}-cache
    image: redis:6
  directus:
    container_name: ddev-${DDEV_SITENAME}-directus
    image: directus/directus:latest
    working_dir: "/directus"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    expose:
      - 8055
    environment:
      - KEY=91c53bcc-a136-458e-82a3-92068eaf9c45
      - SECRET=fae57a30-b343-48a3-8cc4-c752fbe6abbc
      - DB_CLIENT=pg
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=db
      - DB_USER=db
      - DB_PASSWORD=db
      - CACHE_ENABLED=true
      - CACHE_STORE=redis
      - REDIS=redis://cache:6379
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=d1r3ctu5
      - CORS_ENABLED=true
      - CORS_ORIGIN=https://agency-os.ddev.site
      - REFRESH_TOKEN_COOKIE_DOMAIN=directus.agency-os.ddev.site
      - EXTENSIONS_AUTO_RELOAD=true
      - WEBSOCKETS_ENABLED=true
      - PUBLIC_URL=https://directus.agency-os.ddev.site
    volumes:
      - ../directus/uploads:/directus/uploads
      - ../directus/extensions:/directus/extensions
    healthcheck:
      interval: 2m0s
      retries: 1
      timeout: 2s
    depends_on:
      - db
      - cache
